import { db } from '@/db/client';
import { exercises } from '@/db/schema';

export type CatalogSeedExercise = {
  name: string;
  muscleGroup: string;
};

export const catalogSeed: CatalogSeedExercise[] = [
  // Chest
  { name: 'Barbell Bench Press', muscleGroup: 'Chest' },
  { name: 'Incline Barbell Bench Press', muscleGroup: 'Chest' },
  { name: 'Decline Barbell Bench Press', muscleGroup: 'Chest' },
  { name: 'Dumbbell Bench Press', muscleGroup: 'Chest' },
  { name: 'Incline Dumbbell Press', muscleGroup: 'Chest' },
  { name: 'Decline Dumbbell Press', muscleGroup: 'Chest' },
  { name: 'Machine Chest Press', muscleGroup: 'Chest' },
  { name: 'Cable Crossover', muscleGroup: 'Chest' },
  { name: 'Pec Deck', muscleGroup: 'Chest' },
  { name: 'Push-Up', muscleGroup: 'Chest' },
  { name: 'Wide Push-Up', muscleGroup: 'Chest' },
  { name: 'Decline Push-Up', muscleGroup: 'Chest' },
  { name: 'Dips', muscleGroup: 'Chest' },
  { name: 'Incline Push-Up', muscleGroup: 'Chest' },
  { name: 'Dumbbell Fly', muscleGroup: 'Chest' },
  { name: 'Svend Press', muscleGroup: 'Chest' },
  { name: 'Floor Press', muscleGroup: 'Chest' },
  { name: 'Band Chest Press', muscleGroup: 'Chest' },
  // Back
  { name: 'Pull-Up', muscleGroup: 'Back' },
  { name: 'Chin-Up', muscleGroup: 'Back' },
  { name: 'Wide-Grip Lat Pulldown', muscleGroup: 'Back' },
  { name: 'Close-Grip Lat Pulldown', muscleGroup: 'Back' },
  { name: 'Bent-Over Barbell Row', muscleGroup: 'Back' },
  { name: 'Pendlay Row', muscleGroup: 'Back' },
  { name: 'Seated Cable Row', muscleGroup: 'Back' },
  { name: 'One-Arm Dumbbell Row', muscleGroup: 'Back' },
  { name: 'Chest-Supported Row', muscleGroup: 'Back' },
  { name: 'T-Bar Row', muscleGroup: 'Back' },
  { name: 'Machine Row', muscleGroup: 'Back' },
  { name: 'Straight-Arm Pulldown', muscleGroup: 'Back' },
  { name: 'Rear Delt Fly', muscleGroup: 'Back' },
  { name: 'Inverted Row', muscleGroup: 'Back' },
  { name: 'Supine Row', muscleGroup: 'Back' },
  { name: 'Dead Hang', muscleGroup: 'Back' },
  { name: 'Back Extension', muscleGroup: 'Back' },
  // Shoulders
  { name: 'Overhead Press', muscleGroup: 'Shoulders' },
  { name: 'Dumbbell Shoulder Press', muscleGroup: 'Shoulders' },
  { name: 'Arnold Press', muscleGroup: 'Shoulders' },
  { name: 'Machine Shoulder Press', muscleGroup: 'Shoulders' },
  { name: 'Lateral Raise', muscleGroup: 'Shoulders' },
  { name: 'Front Raise', muscleGroup: 'Shoulders' },
  { name: 'Face Pull', muscleGroup: 'Shoulders' },
  { name: 'Upright Row', muscleGroup: 'Shoulders' },
  { name: 'Handstand Push-Up', muscleGroup: 'Shoulders' },
  { name: 'Pike Push-Up', muscleGroup: 'Shoulders' },
  { name: 'Barbell Shrug', muscleGroup: 'Shoulders' },
  { name: 'Dumbbell Shrug', muscleGroup: 'Shoulders' },
  { name: 'Landmine Press', muscleGroup: 'Shoulders' },
  { name: 'Cable Lateral Raise', muscleGroup: 'Shoulders' },
  // Biceps
  { name: 'Barbell Curl', muscleGroup: 'Biceps' },
  { name: 'EZ-Bar Curl', muscleGroup: 'Biceps' },
  { name: 'Dumbbell Curl', muscleGroup: 'Biceps' },
  { name: 'Hammer Curl', muscleGroup: 'Biceps' },
  { name: 'Preacher Curl', muscleGroup: 'Biceps' },
  { name: 'Incline Dumbbell Curl', muscleGroup: 'Biceps' },
  { name: 'Concentration Curl', muscleGroup: 'Biceps' },
  { name: 'Cable Curl', muscleGroup: 'Biceps' },
  { name: 'Reverse Curl', muscleGroup: 'Biceps' },
  // Triceps
  { name: 'Triceps Pushdown', muscleGroup: 'Triceps' },
  { name: 'Rope Pushdown', muscleGroup: 'Triceps' },
  { name: 'Overhead Triceps Extension', muscleGroup: 'Triceps' },
  { name: 'Skull Crusher', muscleGroup: 'Triceps' },
  { name: 'Close-Grip Bench Press', muscleGroup: 'Triceps' },
  { name: 'Diamond Push-Up', muscleGroup: 'Triceps' },
  { name: 'Bench Dips', muscleGroup: 'Triceps' },
  { name: 'Triceps Kickback', muscleGroup: 'Triceps' },
  { name: 'French Press', muscleGroup: 'Triceps' },
  { name: 'Cable Overhead Extension', muscleGroup: 'Triceps' },
  // Forearms
  { name: 'Wrist Curl', muscleGroup: 'Forearms' },
  { name: 'Reverse Wrist Curl', muscleGroup: 'Forearms' },
  { name: "Farmer's Carry", muscleGroup: 'Forearms' },
  { name: 'Wrist Roller', muscleGroup: 'Forearms' },
  { name: 'Plate Pinch', muscleGroup: 'Forearms' },
  // Quads
  { name: 'Back Squat', muscleGroup: 'Quads' },
  { name: 'Front Squat', muscleGroup: 'Quads' },
  { name: 'Goblet Squat', muscleGroup: 'Quads' },
  { name: 'Box Squat', muscleGroup: 'Quads' },
  { name: 'Leg Press', muscleGroup: 'Quads' },
  { name: 'Leg Extension', muscleGroup: 'Quads' },
  { name: 'Hack Squat', muscleGroup: 'Quads' },
  { name: 'Bulgarian Split Squat', muscleGroup: 'Quads' },
  { name: 'Walking Lunge', muscleGroup: 'Quads' },
  { name: 'Reverse Lunge', muscleGroup: 'Quads' },
  { name: 'Pistol Squat', muscleGroup: 'Quads' },
  { name: 'Step-Up', muscleGroup: 'Quads' },
  { name: 'Wall Sit', muscleGroup: 'Quads' },
  { name: 'Sissy Squat', muscleGroup: 'Quads' },
  // Hamstrings
  { name: 'Romanian Deadlift', muscleGroup: 'Hamstrings' },
  { name: 'Barbell Deadlift', muscleGroup: 'Hamstrings' },
  { name: 'Sumo Deadlift', muscleGroup: 'Hamstrings' },
  { name: 'Lying Leg Curl', muscleGroup: 'Hamstrings' },
  { name: 'Seated Leg Curl', muscleGroup: 'Hamstrings' },
  { name: 'Nordic Curl', muscleGroup: 'Hamstrings' },
  { name: 'Good Morning', muscleGroup: 'Hamstrings' },
  { name: 'Glute-Ham Raise', muscleGroup: 'Hamstrings' },
  { name: 'Straight-Leg Deadlift', muscleGroup: 'Hamstrings' },
  { name: 'Single-Leg Romanian Deadlift', muscleGroup: 'Hamstrings' },
  // Glutes
  { name: 'Hip Thrust', muscleGroup: 'Glutes' },
  { name: 'Glute Bridge', muscleGroup: 'Glutes' },
  { name: 'Cable Kickback', muscleGroup: 'Glutes' },
  { name: 'Kettlebell Swing', muscleGroup: 'Glutes' },
  { name: 'Sumo Squat', muscleGroup: 'Glutes' },
  { name: 'Frog Pump', muscleGroup: 'Glutes' },
  { name: 'Hip Abduction', muscleGroup: 'Glutes' },
  // Calves
  { name: 'Standing Calf Raise', muscleGroup: 'Calves' },
  { name: 'Seated Calf Raise', muscleGroup: 'Calves' },
  { name: 'Donkey Calf Raise', muscleGroup: 'Calves' },
  { name: 'Leg Press Calf Raise', muscleGroup: 'Calves' },
  { name: 'Single-Leg Calf Raise', muscleGroup: 'Calves' },
  { name: 'Box Jump', muscleGroup: 'Calves' },
  // Core
  { name: 'Plank', muscleGroup: 'Core' },
  { name: 'Side Plank', muscleGroup: 'Core' },
  { name: 'Hanging Leg Raise', muscleGroup: 'Core' },
  { name: 'Hanging Knee Raise', muscleGroup: 'Core' },
  { name: 'Ab Wheel Rollout', muscleGroup: 'Core' },
  { name: 'Russian Twist', muscleGroup: 'Core' },
  { name: 'Crunch', muscleGroup: 'Core' },
  { name: 'Sit-Up', muscleGroup: 'Core' },
  { name: 'Cable Crunch', muscleGroup: 'Core' },
  { name: 'L-Sit', muscleGroup: 'Core' },
  { name: 'Hollow Body Hold', muscleGroup: 'Core' },
  { name: 'Dead Bug', muscleGroup: 'Core' },
  { name: 'Mountain Climber', muscleGroup: 'Core' },
  { name: 'V-Up', muscleGroup: 'Core' },
  { name: 'Pallof Press', muscleGroup: 'Core' },
  { name: 'Turkish Get-Up', muscleGroup: 'Core' },
  { name: 'Barbell Rollout', muscleGroup: 'Core' },
  // Full body
  { name: 'Burpee', muscleGroup: 'Full body' },
  { name: 'Clean and Press', muscleGroup: 'Full body' },
  { name: 'Thruster', muscleGroup: 'Full body' },
  { name: 'Ring Muscle-Up', muscleGroup: 'Full body' },
  { name: 'Bear Crawl', muscleGroup: 'Full body' },
  { name: 'Snatch', muscleGroup: 'Full body' },
  { name: "Devil's Press", muscleGroup: 'Full body' },
  { name: 'Bear Complex', muscleGroup: 'Full body' },
];

export async function seedExerciseCatalog(): Promise<number> {
  const existing = await db.select({ name: exercises.name }).from(exercises);
  const known = new Set(existing.map((row) => row.name.trim().toLowerCase()));
  const missing = catalogSeed.filter((entry) => !known.has(entry.name.trim().toLowerCase()));
  if (missing.length === 0) return 0;
  await db.insert(exercises).values(missing);
  return missing.length;
}
